Forward Propagation purely implemented in Python


First we implement the code with complete for loops, without using any vectorization or library

In [18]:
import numpy as np

In [20]:
# Lets define our input vector with two features
x = np.array([200, 17])


In [40]:
# Layer 1 has 3 neurons so it can be modeled as,

#unit_1 of Layer 1
w1_1 = np.array([1,2])
b1_1 = np.array([-1])
z1_1 = np.dot(w1_1,x)+b1_1
a1_1 = 1/(1+np.exp(-z1_1))

#unit_2 of Layer 1
w1_2 = np.array([-3,4])
b1_2 = np.array([1])
z1_2 = np.dot(w1_2,x)+b1_2
a1_2 = 1/(1+np.exp(-z1_2))

#unit_3 of Layer 1
w1_3 = np.array([5,-6])
b1_3 = np.array([2])
z1_3 = np.dot(w1_3,x)+b1_3
a1_3 = 1/(1+np.exp(-z1_3))


In [39]:
#Layer 2 is output layer with one unit
# a1 with three values is input to this layer so lets first convert it into a vector

a1 = np.array([a1_1 , a1_2, a1_3])

#NOw lets model the unit of the final output layer
w2_1 = np.array([-7,8,9])
b2_1 = np.array([3])
z2_1 = np.dot(w2_1,a1)+b2_1
a2_1 = 1/(1+np.exp(-z2_1))
#Now lets print the out put of the final layer
print(f'The output of the NN is: {a2_1}')


The output of the NN is: [0.99330715]


**Now lets implement the given forward propagtion network with Numpy**

In [80]:
#Combining all weights of layer 1 in matrix
W1 = np.array([[1, -3, 5],[2, 4, 6]])
b1 = np.array([-1, 1, 2])
#input feature vector
a_in = np.array([200, 17])
#defining parameters of layer 2
W2= np.array([-7, 8, 9])
b2= np.array([3])


In [81]:
#function to compute layer parameters
def dense(W, b, a_in):
    units = W.shape[1]
    print("total units in this layer are :", units)
    a_out = np.zeros(units)
    for j in range(units):
        w = W[:,j]
        z = np.dot(W[:,j], a_in)+ b[j]
        a_out[j] = 1/(1+np.exp(-z))
        print(a_out[j])
    return a_out


In [94]:
a1= np.zeros(W1[1])
a1= dense(W1, b1, a_in)

total units in this layer are : 3
1.0
2.4526191187752155e-231
1.0


In [110]:
a1= np.transpose(a1)
a1
a2=dense(W2, b2, a1)

IndexError: tuple index out of range

NOw lets with vectorized numpy implementation without using any for loops

In [108]:
def dense1 (A_in, W, b):
    z= np.matmul(A_in, W)+b
    A_out = np.matrix(1/(1+np.exp(-z)))
    print (A_out)
    return np.transpose(A_out)

In [109]:
dense1(x,W1,b1)

[[1.00000000e+000 2.45261912e-231 1.00000000e+000]]


matrix([[1.00000000e+000],
        [2.45261912e-231],
        [1.00000000e+000]])

In [114]:
#train neural network in tensorflow

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
 

In [117]:
model = Sequential([ Dense(units=25, activation = 'sigmoid'),
                    Dense(units=15, activation = 'sigmoid'),
                    Dense(units=1, activation =  'sigmoid'),])

In [118]:
from tensorflow.keras.losses import BinaryCrossentropy

In [120]:
model.compile(loss= BinaryCrossentropy)

In [140]:
X=x
X = np.append(X, [200,300,7])
print(X)
Y= np.array([1,0, 1,1, 0])
model.fit(X,Y, epochs=100)

[200  17 200 300   7]
Epoch 1/100


ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1126, in train_step
        y_pred = self(x, training=True)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/input_spec.py", line 253, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential_1' (type Sequential).
    
    Input 0 of layer "dense_4" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)
    
    Call arguments received by layer 'sequential_1' (type Sequential):
      • inputs=tf.Tensor(shape=(None,), dtype=int64)
      • training=True
      • mask=None
